name: "Mi primer workflow"

on:
  workflow_dispatch:
  
  push:
     branches: 
      - main
      - feature/*
      
      
jobs:
  compile: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
        
